<a href="https://colab.research.google.com/github/park-jiha/deep-learning/blob/main/%EB%AA%A8%EB%8D%B8_%EC%84%A4%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **10장 모델 설계하기**

## 폐암 수술 환자의 생존율 예측

* 데이터를 불러오기 위해 pandas 라이브러리를 사용

In [1]:
import io
import pandas as pd

* 데이터 불러오기

In [2]:
data_pandas = pd.read_csv('ThoraricSurgery.csv',header=None)

In [3]:
data_pandas

      0   1     2     3   4   5   6   7   ...  10  11  12  13  14  15  16  17
0    293   1  3.80  2.80   0   0   0   0  ...  12   0   0   0   1   0  62   0
1      1   2  2.88  2.16   1   0   0   0  ...  14   0   0   0   1   0  60   0
2      8   2  3.19  2.50   1   0   0   0  ...  11   0   0   1   1   0  66   1
3     14   2  3.98  3.06   2   0   0   0  ...  14   0   0   0   1   0  80   1
4     17   2  2.21  1.88   0   0   1   0  ...  12   0   0   0   1   0  56   0
..   ...  ..   ...   ...  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
465   98   6  3.04  2.40   2   0   0   0  ...  11   0   0   0   1   0  76   0
466  369   6  3.88  2.72   1   0   0   0  ...  12   0   0   0   1   0  77   0
467  406   6  5.36  3.96   1   0   0   0  ...  12   0   0   0   0   0  62   0
468   25   8  4.32  3.20   0   0   0   0  ...  11   0   0   0   0   0  58   1
469  447   8  5.20  4.10   0   0   0   0  ...  12   0   0   0   0   0  49   0

[470 rows x 18 columns]

* 케라스 함수 호출하고 numpy 불러오기

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
import numpy as np

* 실행할 때마다 같은 결과를 출력하기 위해서 seed값 설정

In [5]:
np.random.seed(3)
tf.random.set_seed(3)

* 속성인 환자의 기록을 X, 클래스인 수술 결과를 Y로 저장
* 인덱싱 : 그 데이터를 가리키는 것

  -- loc : 인덱스 이름으로 직접 참조

  -- iloc : 정수 인덱스값

* 슬라이싱 : 데이터를 자르는 것

In [6]:
#[행, 열]
#[시작점:끝점, 시작점:끝점]
# : 앞뒤에 아무것도 적지 않으면 '다'라는 뜻
X=data_pandas.iloc[:,:17]
Y=data_pandas.iloc[:,17]
X

      0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16
0    293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62
1      1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60
2      8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66
3     14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80
4     17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56
..   ...  ..   ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
465   98   6  3.04  2.40   2   0   0   0   1   0  11   0   0   0   1   0  76
466  369   6  3.88  2.72   1   0   0   0   1   0  12   0   0   0   1   0  77
467  406   6  5.36  3.96   1   0   0   0   1   0  12   0   0   0   0   0  62
468   25   8  4.32  3.20   0   0   0   0   0   0  11   0   0   0   0   0  58
469  447   8  5.20  4.10   0   0   0   0   0   0  12   0   0   0   0   0  49

[470 rows x 17 columns]

In [7]:
Y

0      0
1      0
2      1
3      1
4      0
      ..
465    0
466    0
467    0
468    1
469    0
Name: 17, Length: 470, dtype: int64

* 모델 구조 결정 (입력층, 은닉층, 출력층)

In [8]:
model=Sequential()
model.add(Dense(30, input_dim=17, activation='relu')) #은닉층
model.add(Dense(1, activation='sigmoid')) #출력층

*!!이제 모델을 실행해보자
!!*

mean_squared_error 와 binary_crossentropy 의 특징을 이해하고 실행 결과를 예측 및 비교

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 1ms/step - loss: 0.1520 - accuracy: 0.8252
Epoch 2/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1240 - accuracy: 0.8713
Epoch 3/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1568 - accuracy: 0.8319
Epoch 4/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1466 - accuracy: 0.8436
Epoch 5/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1343 - accuracy: 0.8526
Epoch 6/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1413 - accuracy: 0.8516
Epoch 7/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1398 - accuracy: 0.8419
Epoch 8/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1380 - accuracy: 0.8468
Epoch 9/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1194 - accuracy: 0.8629
Epoch 10/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1230 - accuracy: 0.8682
Epoch 11/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1472 - accuracy: 0.8482
Epoch 12/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1457 - accuracy: 0.8410
Epoch 13/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1551 - accuracy: 0.8261
Epoch 14/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1462 - accuracy: 0.8437
Epoch 15/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1400 - accuracy: 0.8465
Epoch 16/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1233 - accuracy: 0.8621
Epoch 17/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1371 - accuracy: 0.8592
Epoch 18/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1379 - accuracy: 0.8562
Epoch 19/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1459 - accuracy: 0.8459
Epoch 20/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1180 - accuracy: 0.8675
Epoch 21/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1409 - accuracy: 0.8484
Epoch 22/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1309 - accuracy: 0.8529
Epoch 23/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1321 - accuracy: 0.8474
Epoch 24/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1400 - accuracy: 0.8495
Epoch 25/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1403 - accuracy: 0.8362
Epoch 26/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1321 - accuracy: 0.8571
Epoch 27/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1310 - accuracy: 0.8496
Epoch 28/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1458 - accuracy: 0.8422
Epoch 29/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1132 - accuracy: 0.8738
Epoch 30/100
47/47 [==============================] - 0s 1ms/step - loss: 0.0989 - accuracy: 0.8893
Epoch 31/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1227 - accuracy: 0.8815
Epoch 32/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1344 - accuracy: 0.8575
Epoch 33/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1323 - accuracy: 0.8558
Epoch 34/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1333 - accuracy: 0.8596
Epoch 35/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1346 - accuracy: 0.8401
Epoch 36/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1509 - accuracy: 0.8263
Epoch 37/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1439 - accuracy: 0.8492
Epoch 38/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1395 - accuracy: 0.8473
Epoch 39/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1385 - accuracy: 0.8477
Epoch 40/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1331 - accuracy: 0.8503
Epoch 41/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1388 - accuracy: 0.8459
Epoch 42/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1285 - accuracy: 0.8585
Epoch 43/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1149 - accuracy: 0.8739
Epoch 44/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1134 - accuracy: 0.8778
Epoch 45/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1420 - accuracy: 0.8530
Epoch 46/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1383 - accuracy: 0.8432
Epoch 47/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1098 - accuracy: 0.8807
Epoch 48/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1266 - accuracy: 0.8643
Epoch 49/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1452 - accuracy: 0.8352
Epoch 50/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1096 - accuracy: 0.8773
Epoch 51/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1273 - accuracy: 0.8465
Epoch 52/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1331 - accuracy: 0.8556
Epoch 53/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1296 - accuracy: 0.8508
Epoch 54/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1415 - accuracy: 0.8355
Epoch 55/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1246 - accuracy: 0.8567
Epoch 56/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1350 - accuracy: 0.8462
Epoch 57/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1265 - accuracy: 0.8469
Epoch 58/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1129 - accuracy: 0.8601
Epoch 59/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1470 - accuracy: 0.8379
Epoch 60/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1104 - accuracy: 0.8760
Epoch 61/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1153 - accuracy: 0.8788
Epoch 62/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1301 - accuracy: 0.8480
Epoch 63/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1185 - accuracy: 0.8605
Epoch 64/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1219 - accuracy: 0.8676
Epoch 65/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1200 - accuracy: 0.8665
Epoch 66/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1266 - accuracy: 0.8499
Epoch 67/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1126 - accuracy: 0.8672
Epoch 68/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1174 - accuracy: 0.8668
Epoch 69/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1418 - accuracy: 0.8272
Epoch 70/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1230 - accuracy: 0.8426
Epoch 71/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1429 - accuracy: 0.8122
Epoch 72/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1154 - accuracy: 0.8624
Epoch 73/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1406 - accuracy: 0.8501
Epoch 74/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1311 - accuracy: 0.8655
Epoch 75/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1080 - accuracy: 0.8836
Epoch 76/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1240 - accuracy: 0.8614
Epoch 77/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1477 - accuracy: 0.8388
Epoch 78/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1154 - accuracy: 0.8699
Epoch 79/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1253 - accuracy: 0.8479
Epoch 80/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1317 - accuracy: 0.8346
Epoch 81/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1125 - accuracy: 0.8786
Epoch 82/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1262 - accuracy: 0.8512
Epoch 83/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1432 - accuracy: 0.8419
Epoch 84/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1001 - accuracy: 0.8812
Epoch 85/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1335 - accuracy: 0.8569
Epoch 86/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1190 - accuracy: 0.8733
Epoch 87/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1173 - accuracy: 0.8684
Epoch 88/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1171 - accuracy: 0.8442
Epoch 89/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1356 - accuracy: 0.8422
Epoch 90/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1153 - accuracy: 0.8736
Epoch 91/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1334 - accuracy: 0.8528
Epoch 92/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1310 - accuracy: 0.8512
Epoch 93/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1305 - accuracy: 0.8428
Epoch 94/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1260 - accuracy: 0.8549
Epoch 95/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1266 - accuracy: 0.8526
Epoch 96/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1202 - accuracy: 0.8652
Epoch 97/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1495 - accuracy: 0.8370
Epoch 98/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1265 - accuracy: 0.8520
Epoch 99/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1160 - accuracy: 0.8748
Epoch 100/100
47/47 [==============================] - 0s 1ms/step - loss: 0.1358 - accuracy: 0.8529